' Auto-generated by build_desktop.py — do not hand-edit unless you know why.
Option Explicit
Dim shell, processEnvironment
Set shell = CreateObject("WScript.Shell")
Set processEnvironment = shell.Environment("PROCESS")
processEnvironment("HERMES_DESKTOP_HERMES_ROOT") = "E:\AI\hermes-agent"
processEnvironment("HERMES_DESKTOP_IGNORE_EXISTING") = "1"
shell.CurrentDirectory = "E:\AI\hermes-agent\apps\desktop\release\win-unpacked"
shell.Run """E:\AI\hermes-agent\apps\desktop\release\win-unpacked\Hermes.exe""", 1, False
