@echo off
REM Auto-generated by build_desktop.py — do not hand-edit unless you know why.
set "HERMES_DESKTOP_HERMES_ROOT=E:\AI\hermes-agent"
set "HERMES_DESKTOP_IGNORE_EXISTING=1"
start "" "E:\AI\hermes-agent\apps\desktop\release\win-unpacked\Hermes.exe"
